name: Compress Images
on:
  pull_request:
    paths:
      - 'src/**/*.jpg'
      - 'src/**/*.jpeg'
      - 'src/**/*.png'
      - 'src/**/*.webp'
jobs:
  build:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Compress Images
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: '82'
          pngQuality: '86'
          webpQuality: '86'
