name: 'Generate OG Images'
on:
  pull_request:
    types: [opened,edited]

jobs:
  generate_og_job:
    runs-on: ubuntu-latest
    name: Generate OG Images
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate Image
        uses: croutonn/generate-og-image@1.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GENERATE_OG_IMAGE }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          path: src/images/post-images/
